### PR TITLE
chore: sylius 1.13 compatibility

### PR DESCRIPTION
**Pull request by fred-dedi**
Hi,

This PR adds sylius 1.13 compatibility.

I am not sure about deleted dev dependencies being really useful in the plugin, but it is compulsory to remove them as they conflicts with doctrine/dbal and psr/log requirements.

### CODE REVIEW

**Comment by chibani** [comment]
Hi @fred-dedi , I was looking for upgrading to Sylius 1.13 and found your PR.
Do you know what failed in the tests (I can't see the jobs logs) ?

**Comment by fred-dedi** [comment]
hi @chibani 

It looks like the github action tried to install sylius 1.13 with php 8.0 and failed.

image

**Comment by chibani** [comment]
PHP 8.0 support has been dropped with Sylius 1.13, so it can't install.

**Comment by fred-dedi** [comment]
@chibani yes i know that, that's why i tried to exclude it from the matrix but it did not work as intended

**Comment by maximehuran** [comment]
Hi @fred-dedi 
See #22

**Pull request closed without merging**
